name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install dependencies
      - run: npm ci
      # End of setup
      - run: |
          npm run build
          npm run test
          npm run lint
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/common/lcov.info